/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicplayerproject;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Feeax
 */
public class MusicPlayerScreen extends javax.swing.JFrame {
    
    MusicPlayer audioPlayer;
    String state;
    String username;
    String curSongName;
    String curArtistName;
    String curGenreName;
    String curSongPath;
    int curSong;
    int curuserid;
    Boolean userState;
    DatabaseService db = new DatabaseService();

    /**
     * Creates new form MusicPlayerScreen
     */
    public MusicPlayerScreen() {
        initComponents();
    }
    
    public MusicPlayerScreen(String username,Boolean user){
        this.username = username;
        audioPlayer = new MusicPlayer();
        initComponents();
        state = "Paused";
        db.getInfo(InfoTable, username);
        userState = true;
        headertext.setText(username + "'s Player");
        curSong = -1;
        curuserid = db.getUserId(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headertext = new javax.swing.JLabel();
        JscrollPane1 = new javax.swing.JScrollPane();
        InfoTable = new javax.swing.JTable();
        BackButton = new javax.swing.JButton();
        VolumeDown = new javax.swing.JButton();
        VolumeUp = new javax.swing.JButton();
        DeleteSongButton = new javax.swing.JButton();
        PlayButton = new javax.swing.JButton();
        PauseButton = new javax.swing.JButton();
        StopButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Header1 = new javax.swing.JLabel();
        CurrentSong = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(117, 163, 163));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headertext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        headertext.setForeground(new java.awt.Color(117, 117, 163));
        jPanel1.add(headertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 900, 60));

        InfoTable.setBackground(new java.awt.Color(179, 204, 204));
        InfoTable.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 3, true));
        InfoTable.setForeground(new java.awt.Color(255, 255, 255));
        InfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Song Name", "Artist", "Genre", "Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        InfoTable.setGridColor(new java.awt.Color(102, 102, 255));
        InfoTable.setSelectionForeground(new java.awt.Color(52, 52, 86));
        InfoTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InfoTableMouseClicked(evt);
            }
        });
        JscrollPane1.setViewportView(InfoTable);

        jPanel1.add(JscrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 740, 140));

        BackButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackButton.setForeground(new java.awt.Color(117, 117, 223));
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        jPanel1.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 80, 40));

        VolumeDown.setText("Volume Down");
        VolumeDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeDownActionPerformed(evt);
            }
        });
        jPanel1.add(VolumeDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, 110, 30));

        VolumeUp.setText("Volume Up");
        VolumeUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeUpActionPerformed(evt);
            }
        });
        jPanel1.add(VolumeUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 110, 30));

        DeleteSongButton.setText("Delete Song");
        DeleteSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteSongButtonActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteSongButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 310, 120, 70));

        PlayButton.setText("Play");
        PlayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlayButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PlayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 70, 70));

        PauseButton.setText("Pause");
        PauseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(PauseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 80, 70));

        StopButton.setText("Stop");
        StopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopButtonActionPerformed(evt);
            }
        });
        jPanel1.add(StopButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 230, 70, 70));

        jPanel2.setBackground(new java.awt.Color(179, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Header1.setForeground(new java.awt.Color(117, 117, 223));
        Header1.setText("Current Song");
        jPanel2.add(Header1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 11, -1, -1));
        jPanel2.add(CurrentSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 450, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 490, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1010, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InfoTableMouseClicked
if(state.equals("Playing")){
        try {
            audioPlayer.stop();
        } catch (Exception ex) {
            Logger.getLogger(MusicPlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        int row = InfoTable.getSelectedRow();
        int songid = (int) InfoTable.getValueAt(row, 0);
        String songName = (String) InfoTable.getValueAt(row, 1);
        String artistName = (String) InfoTable.getValueAt(row, 2);
        String genreName = (String) InfoTable.getValueAt(row, 3);
        String songPath = (String) InfoTable.getValueAt(row, 4);
       
        audioPlayer.setFilePath(db.getPath(songid));
        try {
            audioPlayer.setStruct();
        } catch (Exception ex) {
            Logger.getLogger(MusicPlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        state = "Playing";
        PlayButton.setEnabled(false);
        PauseButton.setEnabled(true);
        CurrentSong.setText(songName + " - " + artistName);
    
        curSongName = songName;
        curArtistName = artistName;
        curGenreName = genreName;
        curSongPath = songPath;
        curSong = songid;
        
     }
    }//GEN-LAST:event_InfoTableMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        UserPlayScreen userScreen = new UserPlayScreen(username);
            userScreen.setVisible(true);
            this.dispose();
            if(state.equals("Playing"))
            {
            try {
            audioPlayer.stop();
            }catch (Exception ex) {
            Logger.getLogger(MusicPlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    }//GEN-LAST:event_BackButtonActionPerformed

    private void VolumeUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeUpActionPerformed
       if(state.equals("Playing")){
            audioPlayer.VolumeUp();
        }
    }//GEN-LAST:event_VolumeUpActionPerformed

    private void DeleteSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteSongButtonActionPerformed
         if(state.equals("Playing")){
            try {
                audioPlayer.stop();
            } catch (Exception ex) {
                Logger.getLogger(MusicPlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        db.deleteSongFromUser(curSong,username);
        MusicPlayerScreen musicplayerscreen;
        try 
        {
            musicplayerscreen = new MusicPlayerScreen(username,userState);
            musicplayerscreen.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(UserPlayScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_DeleteSongButtonActionPerformed

    private void VolumeDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeDownActionPerformed
         if(state.equals("Playing")){
            audioPlayer.VolumeDown();
        }
    }//GEN-LAST:event_VolumeDownActionPerformed

    private void PlayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlayButtonActionPerformed
        if (state.equals("Paused")) {
            PauseButton.setEnabled(true);
            PlayButton.setEnabled(false);
            try {
                audioPlayer.resume();
            } catch (Exception ex) {
                Logger.getLogger(MusicPlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
            state = "Playing";
        }
    }//GEN-LAST:event_PlayButtonActionPerformed

    private void PauseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseButtonActionPerformed
        PauseButton.setEnabled(false);
                if (state.equals("Playing")) {
                    PlayButton.setEnabled(true);
                    audioPlayer.pause();
                    state = "Paused";
                } else if (state.equals("Base")) {
                    PauseButton.setEnabled(true);
                }
    }//GEN-LAST:event_PauseButtonActionPerformed

    private void StopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopButtonActionPerformed
     StopButton.setEnabled(true);
                PauseButton.setEnabled(true);
                PlayButton.setEnabled(true);
                if(state.equals("Playing")){
                    audioPlayer.pause();
                    try {
                        audioPlayer.stop();
                    } catch (Exception ex) {
                        Logger.getLogger(MusicPlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if(state.equals("Paused")){
                    try {
                        audioPlayer.stop();
                    } catch (Exception ex) {
                        Logger.getLogger(MusicPlayerScreen.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

                state = "Base";
    }//GEN-LAST:event_StopButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicPlayerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicPlayerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicPlayerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicPlayerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicPlayerScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CurrentSong;
    private javax.swing.JButton DeleteSongButton;
    private javax.swing.JLabel Header1;
    private javax.swing.JTable InfoTable;
    private javax.swing.JScrollPane JscrollPane1;
    private javax.swing.JButton PauseButton;
    private javax.swing.JButton PlayButton;
    private javax.swing.JButton StopButton;
    private javax.swing.JButton VolumeDown;
    private javax.swing.JButton VolumeUp;
    private javax.swing.JLabel headertext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
