/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicplayerproject;

import javax.swing.JOptionPane;

/**
 *
 * @author Feeax
 */
public class RegisterScreen extends javax.swing.JFrame {
    DatabaseService db = new DatabaseService();

    /**
     * Creates new form RegisterScreen
     */
    public RegisterScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Register = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        ReEnterPassword = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        PasswordField2 = new javax.swing.JPasswordField();
        EmailField = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        LoginButton = new javax.swing.JButton();
        ExistingAccount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(117, 163, 163));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(179, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Register.setForeground(new java.awt.Color(117, 117, 223));
        Register.setText("Register");
        jPanel2.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        Username.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Username.setForeground(new java.awt.Color(117, 117, 223));
        Username.setText("Username");
        jPanel2.add(Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        Password.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Password.setForeground(new java.awt.Color(117, 117, 223));
        Password.setText("Password");
        jPanel2.add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        ReEnterPassword.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        ReEnterPassword.setForeground(new java.awt.Color(117, 117, 223));
        ReEnterPassword.setText("Re-enter Password");
        jPanel2.add(ReEnterPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, -1, -1));

        Email.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Email.setForeground(new java.awt.Color(117, 117, 223));
        Email.setText("E-mail");
        jPanel2.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));
        jPanel2.add(UsernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 160, -1));
        jPanel2.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 160, -1));
        jPanel2.add(PasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 160, -1));
        jPanel2.add(EmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 160, -1));

        RegisterButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(117, 117, 223));
        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        jPanel2.add(RegisterButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        LoginButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(117, 117, 223));
        LoginButton.setText("Login");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        ExistingAccount.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ExistingAccount.setForeground(new java.awt.Color(117, 117, 163));
        ExistingAccount.setText("Already have an account?");
        jPanel2.add(ExistingAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 410, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        LoginScreen loginScreen = new LoginScreen();
        loginScreen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
       String username = UsernameField.getText();
        String password = PasswordField.getText();
        String rePassword = PasswordField2.getText();
        String email = EmailField.getText();
        
        if(!db.checkLogin(username))
        {
            if(password.equals(rePassword)){
                db.createAccount(username, password, email);
                JOptionPane.showMessageDialog(null, "Account has been succesfully created !");
                LoginScreen loginScreen = new LoginScreen();
                loginScreen.setVisible(true);
                this.dispose();
            }else JOptionPane.showMessageDialog(null, "Passwords dont match!");

        }else JOptionPane.showMessageDialog(null, "User already exists!");
    }//GEN-LAST:event_RegisterButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel ExistingAccount;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JPasswordField PasswordField2;
    private javax.swing.JLabel ReEnterPassword;
    private javax.swing.JLabel Register;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel Username;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
