/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicplayerproject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Feeax
 */
public class UserPlayScreen extends javax.swing.JFrame {
    DatabaseService db = new DatabaseService();
    String choosesongpath;
    String chooseusername;

    /**
     * Creates new form UserPlayScreen
     */
    public UserPlayScreen() {
        initComponents();
    }

    public UserPlayScreen(String username)
    {
        this.chooseusername = username;
        initComponents();
        String inittext =  " Welcome back " +  username + " , enjoy your time.";
        headertext.setText(inittext);
        db.createUserSongTable(username);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MainName = new javax.swing.JLabel();
        SongNameField = new javax.swing.JTextField();
        SongName = new javax.swing.JLabel();
        GenreName = new javax.swing.JLabel();
        GenreNameField = new javax.swing.JTextField();
        ArtistName = new javax.swing.JLabel();
        ArtistNameField = new javax.swing.JTextField();
        Explanation = new javax.swing.JLabel();
        ChooseSongButton = new javax.swing.JButton();
        AddSongButton = new javax.swing.JButton();
        LogOutButton = new javax.swing.JButton();
        MusicPlayerButton = new javax.swing.JButton();
        headertext = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(117, 163, 163));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(179, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainName.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        MainName.setForeground(new java.awt.Color(117, 117, 223));
        MainName.setText("Add Song");
        jPanel2.add(MainName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 190, -1));
        jPanel2.add(SongNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 280, -1));

        SongName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SongName.setForeground(new java.awt.Color(117, 117, 223));
        SongName.setText("Song Name");
        jPanel2.add(SongName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        GenreName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GenreName.setForeground(new java.awt.Color(117, 117, 223));
        GenreName.setText("Genre");
        jPanel2.add(GenreName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));
        jPanel2.add(GenreNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 280, -1));

        ArtistName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ArtistName.setForeground(new java.awt.Color(117, 117, 223));
        ArtistName.setText("Artist");
        jPanel2.add(ArtistName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, -1, -1));
        jPanel2.add(ArtistNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 280, -1));

        Explanation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Explanation.setForeground(new java.awt.Color(117, 117, 163));
        Explanation.setText("Please choose a song with .wav extension.");
        Explanation.setToolTipText("");
        jPanel2.add(Explanation, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        ChooseSongButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ChooseSongButton.setForeground(new java.awt.Color(117, 117, 223));
        ChooseSongButton.setText("Choose Song");
        ChooseSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChooseSongButtonActionPerformed(evt);
            }
        });
        jPanel2.add(ChooseSongButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 130, 50));

        AddSongButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddSongButton.setForeground(new java.awt.Color(117, 117, 223));
        AddSongButton.setText("Add Song");
        AddSongButton.setToolTipText("");
        AddSongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSongButtonActionPerformed(evt);
            }
        });
        jPanel2.add(AddSongButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 140, 50));

        LogOutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LogOutButton.setForeground(new java.awt.Color(117, 117, 223));
        LogOutButton.setText("Log Out");
        LogOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutButtonActionPerformed(evt);
            }
        });
        jPanel2.add(LogOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 100, 40));

        MusicPlayerButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MusicPlayerButton.setForeground(new java.awt.Color(117, 117, 223));
        MusicPlayerButton.setText("Music Player");
        MusicPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MusicPlayerButtonActionPerformed(evt);
            }
        });
        jPanel2.add(MusicPlayerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 120, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 610, 490));

        headertext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        headertext.setForeground(new java.awt.Color(117, 117, 163));
        jPanel1.add(headertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 670, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 596, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSongButtonActionPerformed
            
        String songname = SongNameField.getText();
        String genrename = GenreNameField.getText();
        String artistname = ArtistNameField.getText();
       
        if(!db.checkSongUser(songname,artistname,chooseusername))
        {
            if(choosesongpath != null){
                db.addSongToUser(songname, artistname, genrename, choosesongpath,chooseusername);
                 JOptionPane.showMessageDialog(null, "Your song has been added to your player !");
            }else JOptionPane.showMessageDialog(null, "Please select a song !");

        }else
        {
           JOptionPane.showMessageDialog(null, "That song seems to be already in your player !");
        }

        

    }//GEN-LAST:event_AddSongButtonActionPerformed

    private void ChooseSongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChooseSongButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showDialog(ChooseSongButton,"Choose file");
        choosesongpath = chooser.getSelectedFile().toString();
    }//GEN-LAST:event_ChooseSongButtonActionPerformed

    private void LogOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutButtonActionPerformed
      LoginScreen loginscreen = new LoginScreen();
      loginscreen.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_LogOutButtonActionPerformed

    private void MusicPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusicPlayerButtonActionPerformed
        MusicPlayerScreen musicPlayerScreen;
        try {
            musicPlayerScreen = new MusicPlayerScreen(chooseusername,true);
            musicPlayerScreen.setVisible(true);
            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(UserPlayScreen.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_MusicPlayerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPlayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPlayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPlayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPlayScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPlayScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSongButton;
    private javax.swing.JLabel ArtistName;
    private javax.swing.JTextField ArtistNameField;
    private javax.swing.JButton ChooseSongButton;
    private javax.swing.JLabel Explanation;
    private javax.swing.JLabel GenreName;
    private javax.swing.JTextField GenreNameField;
    private javax.swing.JButton LogOutButton;
    private javax.swing.JLabel MainName;
    private javax.swing.JButton MusicPlayerButton;
    private javax.swing.JLabel SongName;
    private javax.swing.JTextField SongNameField;
    private javax.swing.JLabel headertext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
